[project]
name = "tarea1"
version = "0.1.0"
description = "Programa Diccionario"
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.10.7",
    "rich>=14.1.0",
]

[project.scripts]
tarea1 = "tarea1:main" 

[build-system]
requires = ["uv_build>=0.8.5,<0.9.0"]
build-backend = "uv_build"
